[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "aoc"
version = "0.1.0"

[dependencies]
cachedir = "0.1.1"
chrono-tz = "0.4.1"
clap = "2.28.0"
failure = "0.1.1"
itertools = "0.7.4"
lazy_static = "1.0.0"
reqwest = "0.8.1"
select = "0.4.2"
serde = "1.0.23"
serde_derive = "1.0.23"
structopt-derive = "0.1.6"
open = "1.2.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.preferences]
git = "https://github.com/Eh2406/preferences-rs"
rev = "4f426cf"
version = "2.0.0"
